# Module manifest for module 'SmartNotes'
# Generated by: Lage Berger Jensen
# Generated on: 20.04.2021

@{
    RootModule        = 'SmartNotes.psm1'
    ModuleVersion     = '0.1.0'
    GUID              = '015c305d-4eee-4092-a251-d427bd3e8b1e'
    Author            = 'Lage Berger Jensen'
    CompanyName       = ''
    Copyright         = '(c) 2020 Lage Berger Jensen. All rights reserved.'
    Description       = ''
    FunctionsToExport = @(
        'ConvertTo-PermanentNote',
        'Get-NotesByKeyword',
        'Get-NotesByTag',
        'Get-NotesByTopic',
        'Move-DailyNotes',
        'New-SmartNote',
        'New-SmartNoteDirectory'
    )
    CmdletsToExport   = @()
    VariablesToExport = @()
    AliasesToExport   = @()
    # CompatiblePSEditions = @()
    # PowerShellVersion = ''
    # PowerShellHostName = ''
    # PowerShellHostVersion = ''
    # DotNetFrameworkVersion = ''
    # CLRVersion = ''
    # ProcessorArchitecture = ''
    # RequiredModules = @()
    # RequiredAssemblies = @()
    # ScriptsToProcess = @()
    # TypesToProcess = @()
    # FormatsToProcess = @()
    # NestedModules = @()
    # DscResourcesToExport = @()
    # ModuleList = @()
    # FileList = @()
    PrivateData       = @{
        PSData = @{
            # Tags = @()
            LicenseUri = 'https://github.com/lagebj/SmartNotes/blob/master/LICENSE'
            ProjectUri = 'https://github.com/lagebj/SmartNotes'
            # IconUri = ''
            ReleaseNotes = 'https://github.com/lagebj/SmartNotes/blob/master/ReleaseNotes.md'
        }
    }
    # HelpInfoURI = ''
    # DefaultCommandPrefix = ''
}
